{
 "title": "ArangoDB",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "#Client connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "arangodb_client_connection_statistics_client_connections",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "arangodb_http_request_statistics_total_requests",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "GET requests [5m]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(arangodb_http_request_statistics_http_get_requests[5m])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "POST/PUT/PATCH requests [5m]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(arangodb_http_request_statistics_http_post_requests[5m])) by (job)",
     "legendFormat": "{{job}}-POST"
    },
    {
     "expr": "sum(increase(arangodb_http_request_statistics_http_put_requests[5m])) by (job)",
     "legendFormat": "{{job}}-PUT"
    },
    {
     "expr": "sum(increase(arangodb_http_request_statistics_http_patch_requests[5m])) by (job)",
     "legendFormat": "{{job}}-PATCH"
    }
   ]
  },
  {
   "title": "DELETE requests [5m]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(arangodb_http_request_statistics_http_delete_requests[5m])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Exporter total scrapes [1m]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(arangodb_exporter_total_scrapes[1m])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Exporter failed scrapes [1h]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(arangodb_exporter_failed_scrapes[1h])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}